apiVersion: apps/v1
kind: Deployment
metadata:
  name: longcache
  labels:
    app: longcache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: longcache
  template:
    metadata:
      labels:
        app: longcache
    spec:
      containers:
        - name: longcache
          image: huzjie/longcache:latest
          ports:
            - containerPort: 8000
          env:
            - name: LONGCACHE_BACKEND
              value: "mock"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
